version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_static_files:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$POSTGRES_USER --dbname=$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  backend_static_files:
  media_volume: